### ISSUE TITLE
你好，你的select0_3宏定义是不能展开的

### ISSUE THREAD

**Issue by liming2013** [CWKSC/MacroLib#2]
你好，你的select0_3宏定义是不能展开的，请问你是用什么编译器的？

**Comment by CWKSC** [comment]
一年過去了，現在才想起來回覆（

當年是用 Visual studio 2017，select 那堆用了不適當/正規的技巧，所以有點問題

新的可以看這個 [https://github.com/CWKSC/MyLib_Cpp_Macro](https://github.com/CWKSC/MyLib_Cpp_Macro)
